name: Deploy to IPNS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jtsmedley/ipfs-action@a1f7b100f040ca9718fb1e8bd50bcf3115acee3b
        with:
          path: ./src
          service: filebase
          pinName: 'ipfs-action'
          filebaseBucket: ${{ vars.FILEBASE_BUCKET }}
          filebaseKey: ${{ secrets.FILEBASE_KEY }}
          filebaseSecret: ${{ secrets.FILEBASE_SECRET }}
          key: ${{ vars.FILEBASE_NAME }}